/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 53
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 40
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 15
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 11
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_palette = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_sprite = 5,
  anon_sym_EQ = 6,
  sym_row_separator = 7,
  anon_sym_fill = 8,
  anon_sym_rect = 9,
  anon_sym_pixel = 10,
  anon_sym_line = 11,
  anon_sym_circle = 12,
  anon_sym_flip = 13,
  anon_sym_COMMA = 14,
  sym_transparent = 15,
  sym_hex_color = 16,
  sym_dimensions = 17,
  sym_integer = 18,
  sym_comment = 19,
  sym_source_file = 20,
  sym__definition = 21,
  sym_palette_decl = 22,
  sym_palette_entry = 23,
  sym_sprite_decl = 24,
  sym_palette_attr = 25,
  sym__body_item = 26,
  sym_cell = 27,
  sym__op = 28,
  sym_fill_op = 29,
  sym_rect_op = 30,
  sym_pixel_op = 31,
  sym_line_op = 32,
  sym_circle_op = 33,
  sym_flip_op = 34,
  sym_coord = 35,
  sym__value = 36,
  aux_sym_source_file_repeat1 = 37,
  aux_sym_palette_decl_repeat1 = 38,
  aux_sym_sprite_decl_repeat1 = 39,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_palette] = "palette",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_sprite] = "sprite",
  [anon_sym_EQ] = "=",
  [sym_row_separator] = "row_separator",
  [anon_sym_fill] = "fill",
  [anon_sym_rect] = "rect",
  [anon_sym_pixel] = "pixel",
  [anon_sym_line] = "line",
  [anon_sym_circle] = "circle",
  [anon_sym_flip] = "flip",
  [anon_sym_COMMA] = ",",
  [sym_transparent] = "transparent",
  [sym_hex_color] = "hex_color",
  [sym_dimensions] = "dimensions",
  [sym_integer] = "integer",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_palette_decl] = "palette_decl",
  [sym_palette_entry] = "palette_entry",
  [sym_sprite_decl] = "sprite_decl",
  [sym_palette_attr] = "palette_attr",
  [sym__body_item] = "_body_item",
  [sym_cell] = "cell",
  [sym__op] = "_op",
  [sym_fill_op] = "fill_op",
  [sym_rect_op] = "rect_op",
  [sym_pixel_op] = "pixel_op",
  [sym_line_op] = "line_op",
  [sym_circle_op] = "circle_op",
  [sym_flip_op] = "flip_op",
  [sym_coord] = "coord",
  [sym__value] = "_value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_palette_decl_repeat1] = "palette_decl_repeat1",
  [aux_sym_sprite_decl_repeat1] = "sprite_decl_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_palette] = anon_sym_palette,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_sprite] = anon_sym_sprite,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_row_separator] = sym_row_separator,
  [anon_sym_fill] = anon_sym_fill,
  [anon_sym_rect] = anon_sym_rect,
  [anon_sym_pixel] = anon_sym_pixel,
  [anon_sym_line] = anon_sym_line,
  [anon_sym_circle] = anon_sym_circle,
  [anon_sym_flip] = anon_sym_flip,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_transparent] = sym_transparent,
  [sym_hex_color] = sym_hex_color,
  [sym_dimensions] = sym_dimensions,
  [sym_integer] = sym_integer,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_palette_decl] = sym_palette_decl,
  [sym_palette_entry] = sym_palette_entry,
  [sym_sprite_decl] = sym_sprite_decl,
  [sym_palette_attr] = sym_palette_attr,
  [sym__body_item] = sym__body_item,
  [sym_cell] = sym_cell,
  [sym__op] = sym__op,
  [sym_fill_op] = sym_fill_op,
  [sym_rect_op] = sym_rect_op,
  [sym_pixel_op] = sym_pixel_op,
  [sym_line_op] = sym_line_op,
  [sym_circle_op] = sym_circle_op,
  [sym_flip_op] = sym_flip_op,
  [sym_coord] = sym_coord,
  [sym__value] = sym__value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_palette_decl_repeat1] = aux_sym_palette_decl_repeat1,
  [aux_sym_sprite_decl_repeat1] = aux_sym_sprite_decl_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_palette] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sprite] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_row_separator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fill] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rect] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pixel] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_line] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_circle] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_flip] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_transparent] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_color] = {
    .visible = true,
    .named = true,
  },
  [sym_dimensions] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_palette_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_palette_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_sprite_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_palette_attr] = {
    .visible = true,
    .named = true,
  },
  [sym__body_item] = {
    .visible = false,
    .named = true,
  },
  [sym_cell] = {
    .visible = true,
    .named = true,
  },
  [sym__op] = {
    .visible = false,
    .named = true,
  },
  [sym_fill_op] = {
    .visible = true,
    .named = true,
  },
  [sym_rect_op] = {
    .visible = true,
    .named = true,
  },
  [sym_pixel_op] = {
    .visible = true,
    .named = true,
  },
  [sym_line_op] = {
    .visible = true,
    .named = true,
  },
  [sym_circle_op] = {
    .visible = true,
    .named = true,
  },
  [sym_flip_op] = {
    .visible = true,
    .named = true,
  },
  [sym_coord] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_palette_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sprite_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_at = 1,
  field_axis = 2,
  field_center = 3,
  field_color = 4,
  field_from = 5,
  field_long = 6,
  field_name = 7,
  field_palette = 8,
  field_radius = 9,
  field_short = 10,
  field_size = 11,
  field_to = 12,
  field_value = 13,
  field_x = 14,
  field_y = 15,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_at] = "at",
  [field_axis] = "axis",
  [field_center] = "center",
  [field_color] = "color",
  [field_from] = "from",
  [field_long] = "long",
  [field_name] = "name",
  [field_palette] = "palette",
  [field_radius] = "radius",
  [field_short] = "short",
  [field_size] = "size",
  [field_to] = "to",
  [field_value] = "value",
  [field_x] = "x",
  [field_y] = "y",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 3},
  [4] = {.index = 6, .length = 1},
  [5] = {.index = 7, .length = 1},
  [6] = {.index = 8, .length = 1},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 3},
  [10] = {.index = 16, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_name, 1},
    {field_size, 2},
  [3] =
    {field_color, 2},
    {field_long, 0},
    {field_short, 1},
  [6] =
    {field_palette, 2},
  [7] =
    {field_value, 1},
  [8] =
    {field_axis, 1},
  [9] =
    {field_at, 1},
    {field_value, 2},
  [11] =
    {field_x, 0},
    {field_y, 2},
  [13] =
    {field_from, 1},
    {field_to, 2},
    {field_value, 3},
  [16] =
    {field_center, 1},
    {field_radius, 2},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '#') ADVANCE(7);
      if (lookahead == ',') ADVANCE(13);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == '/') ADVANCE(12);
      if (lookahead == '=') ADVANCE(11);
      if (lookahead == '{') ADVANCE(9);
      if (lookahead == '}') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 1:
      if (lookahead == '/') ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == 'x') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(5);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(6);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_row_separator);
      if (lookahead == '/') ADVANCE(24);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_transparent);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_hex_color);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_hex_color);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_hex_color);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_hex_color);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_hex_color);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_hex_color);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_dimensions);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'c') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'l') ADVANCE(3);
      if (lookahead == 'p') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(5);
      if (lookahead == 's') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'i') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'i') ADVANCE(8);
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'i') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(11);
      if (lookahead == 'i') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead == 'p') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == 'x') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(21);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead == 'p') ADVANCE(25);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(30);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_fill);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_flip);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_line);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_rect);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_pixel);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_circle);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_sprite);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_palette);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_palette] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_sprite] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_row_separator] = ACTIONS(1),
    [anon_sym_fill] = ACTIONS(1),
    [anon_sym_rect] = ACTIONS(1),
    [anon_sym_pixel] = ACTIONS(1),
    [anon_sym_line] = ACTIONS(1),
    [anon_sym_circle] = ACTIONS(1),
    [anon_sym_flip] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_transparent] = ACTIONS(1),
    [sym_hex_color] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(39),
    [sym__definition] = STATE(15),
    [sym_palette_decl] = STATE(15),
    [sym_sprite_decl] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_palette] = ACTIONS(7),
    [anon_sym_sprite] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__body_item] = STATE(3),
    [sym_cell] = STATE(3),
    [sym__op] = STATE(3),
    [sym_fill_op] = STATE(3),
    [sym_rect_op] = STATE(3),
    [sym_pixel_op] = STATE(3),
    [sym_line_op] = STATE(3),
    [sym_circle_op] = STATE(3),
    [sym_flip_op] = STATE(3),
    [sym__value] = STATE(7),
    [aux_sym_sprite_decl_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(13),
    [sym_row_separator] = ACTIONS(15),
    [anon_sym_fill] = ACTIONS(17),
    [anon_sym_rect] = ACTIONS(19),
    [anon_sym_pixel] = ACTIONS(21),
    [anon_sym_line] = ACTIONS(23),
    [anon_sym_circle] = ACTIONS(25),
    [anon_sym_flip] = ACTIONS(27),
    [sym_transparent] = ACTIONS(29),
    [sym_hex_color] = ACTIONS(29),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__body_item] = STATE(3),
    [sym_cell] = STATE(3),
    [sym__op] = STATE(3),
    [sym_fill_op] = STATE(3),
    [sym_rect_op] = STATE(3),
    [sym_pixel_op] = STATE(3),
    [sym_line_op] = STATE(3),
    [sym_circle_op] = STATE(3),
    [sym_flip_op] = STATE(3),
    [sym__value] = STATE(7),
    [aux_sym_sprite_decl_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(34),
    [sym_row_separator] = ACTIONS(36),
    [anon_sym_fill] = ACTIONS(39),
    [anon_sym_rect] = ACTIONS(42),
    [anon_sym_pixel] = ACTIONS(45),
    [anon_sym_line] = ACTIONS(48),
    [anon_sym_circle] = ACTIONS(51),
    [anon_sym_flip] = ACTIONS(54),
    [sym_transparent] = ACTIONS(57),
    [sym_hex_color] = ACTIONS(57),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym__body_item] = STATE(5),
    [sym_cell] = STATE(5),
    [sym__op] = STATE(5),
    [sym_fill_op] = STATE(5),
    [sym_rect_op] = STATE(5),
    [sym_pixel_op] = STATE(5),
    [sym_line_op] = STATE(5),
    [sym_circle_op] = STATE(5),
    [sym_flip_op] = STATE(5),
    [sym__value] = STATE(7),
    [aux_sym_sprite_decl_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(60),
    [sym_row_separator] = ACTIONS(62),
    [anon_sym_fill] = ACTIONS(17),
    [anon_sym_rect] = ACTIONS(19),
    [anon_sym_pixel] = ACTIONS(21),
    [anon_sym_line] = ACTIONS(23),
    [anon_sym_circle] = ACTIONS(25),
    [anon_sym_flip] = ACTIONS(27),
    [sym_transparent] = ACTIONS(29),
    [sym_hex_color] = ACTIONS(29),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__body_item] = STATE(3),
    [sym_cell] = STATE(3),
    [sym__op] = STATE(3),
    [sym_fill_op] = STATE(3),
    [sym_rect_op] = STATE(3),
    [sym_pixel_op] = STATE(3),
    [sym_line_op] = STATE(3),
    [sym_circle_op] = STATE(3),
    [sym_flip_op] = STATE(3),
    [sym__value] = STATE(7),
    [aux_sym_sprite_decl_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(64),
    [sym_row_separator] = ACTIONS(15),
    [anon_sym_fill] = ACTIONS(17),
    [anon_sym_rect] = ACTIONS(19),
    [anon_sym_pixel] = ACTIONS(21),
    [anon_sym_line] = ACTIONS(23),
    [anon_sym_circle] = ACTIONS(25),
    [anon_sym_flip] = ACTIONS(27),
    [sym_transparent] = ACTIONS(29),
    [sym_hex_color] = ACTIONS(29),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym__body_item] = STATE(2),
    [sym_cell] = STATE(2),
    [sym__op] = STATE(2),
    [sym_fill_op] = STATE(2),
    [sym_rect_op] = STATE(2),
    [sym_pixel_op] = STATE(2),
    [sym_line_op] = STATE(2),
    [sym_circle_op] = STATE(2),
    [sym_flip_op] = STATE(2),
    [sym__value] = STATE(7),
    [aux_sym_sprite_decl_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(64),
    [sym_row_separator] = ACTIONS(66),
    [anon_sym_fill] = ACTIONS(17),
    [anon_sym_rect] = ACTIONS(19),
    [anon_sym_pixel] = ACTIONS(21),
    [anon_sym_line] = ACTIONS(23),
    [anon_sym_circle] = ACTIONS(25),
    [anon_sym_flip] = ACTIONS(27),
    [sym_transparent] = ACTIONS(29),
    [sym_hex_color] = ACTIONS(29),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 3,
      anon_sym_RBRACE,
      sym_transparent,
      sym_hex_color,
    ACTIONS(68), 8,
      sym_row_separator,
      anon_sym_fill,
      anon_sym_rect,
      anon_sym_pixel,
      anon_sym_line,
      anon_sym_circle,
      anon_sym_flip,
      sym_identifier,
  [19] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 3,
      anon_sym_RBRACE,
      sym_transparent,
      sym_hex_color,
    ACTIONS(72), 8,
      sym_row_separator,
      anon_sym_fill,
      anon_sym_rect,
      anon_sym_pixel,
      anon_sym_line,
      anon_sym_circle,
      anon_sym_flip,
      sym_identifier,
  [38] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 3,
      anon_sym_RBRACE,
      sym_transparent,
      sym_hex_color,
    ACTIONS(76), 8,
      sym_row_separator,
      anon_sym_fill,
      anon_sym_rect,
      anon_sym_pixel,
      anon_sym_line,
      anon_sym_circle,
      anon_sym_flip,
      sym_identifier,
  [57] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 3,
      anon_sym_RBRACE,
      sym_transparent,
      sym_hex_color,
    ACTIONS(80), 8,
      sym_row_separator,
      anon_sym_fill,
      anon_sym_rect,
      anon_sym_pixel,
      anon_sym_line,
      anon_sym_circle,
      anon_sym_flip,
      sym_identifier,
  [76] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 3,
      anon_sym_RBRACE,
      sym_transparent,
      sym_hex_color,
    ACTIONS(84), 8,
      sym_row_separator,
      anon_sym_fill,
      anon_sym_rect,
      anon_sym_pixel,
      anon_sym_line,
      anon_sym_circle,
      anon_sym_flip,
      sym_identifier,
  [95] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 3,
      anon_sym_RBRACE,
      sym_transparent,
      sym_hex_color,
    ACTIONS(88), 8,
      sym_row_separator,
      anon_sym_fill,
      anon_sym_rect,
      anon_sym_pixel,
      anon_sym_line,
      anon_sym_circle,
      anon_sym_flip,
      sym_identifier,
  [114] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 3,
      anon_sym_RBRACE,
      sym_transparent,
      sym_hex_color,
    ACTIONS(92), 8,
      sym_row_separator,
      anon_sym_fill,
      anon_sym_rect,
      anon_sym_pixel,
      anon_sym_line,
      anon_sym_circle,
      anon_sym_flip,
      sym_identifier,
  [133] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    ACTIONS(98), 1,
      anon_sym_palette,
    ACTIONS(101), 1,
      anon_sym_sprite,
    STATE(14), 4,
      sym__definition,
      sym_palette_decl,
      sym_sprite_decl,
      aux_sym_source_file_repeat1,
  [152] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_palette,
    ACTIONS(9), 1,
      anon_sym_sprite,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    STATE(14), 4,
      sym__definition,
      sym_palette_decl,
      sym_sprite_decl,
      aux_sym_source_file_repeat1,
  [171] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(9), 1,
      sym__value,
    ACTIONS(106), 3,
      sym_transparent,
      sym_hex_color,
      sym_identifier,
  [183] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 1,
      sym_identifier,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    STATE(17), 2,
      sym_palette_entry,
      aux_sym_palette_decl_repeat1,
  [197] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      sym_identifier,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    STATE(17), 2,
      sym_palette_entry,
      aux_sym_palette_decl_repeat1,
  [211] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      sym_identifier,
    ACTIONS(117), 1,
      anon_sym_RBRACE,
    STATE(18), 2,
      sym_palette_entry,
      aux_sym_palette_decl_repeat1,
  [225] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(12), 1,
      sym__value,
    ACTIONS(119), 3,
      sym_transparent,
      sym_hex_color,
      sym_identifier,
  [237] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(10), 1,
      sym__value,
    ACTIONS(121), 3,
      sym_transparent,
      sym_hex_color,
      sym_identifier,
  [249] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(8), 1,
      sym__value,
    ACTIONS(123), 3,
      sym_transparent,
      sym_hex_color,
      sym_identifier,
  [261] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 4,
      sym_transparent,
      sym_hex_color,
      sym_integer,
      sym_identifier,
  [271] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(13), 1,
      sym__value,
    ACTIONS(127), 3,
      sym_transparent,
      sym_hex_color,
      sym_identifier,
  [283] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 3,
      ts_builtin_sym_end,
      anon_sym_palette,
      anon_sym_sprite,
  [292] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 3,
      ts_builtin_sym_end,
      anon_sym_palette,
      anon_sym_sprite,
  [301] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_palette,
    ACTIONS(135), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_palette_attr,
  [314] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 3,
      ts_builtin_sym_end,
      anon_sym_palette,
      anon_sym_sprite,
  [323] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 3,
      ts_builtin_sym_end,
      anon_sym_palette,
      anon_sym_sprite,
  [332] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 3,
      ts_builtin_sym_end,
      anon_sym_palette,
      anon_sym_sprite,
  [341] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_integer,
    STATE(37), 1,
      sym_coord,
  [351] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_integer,
    STATE(36), 1,
      sym_coord,
  [361] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_integer,
    STATE(21), 1,
      sym_coord,
  [371] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_integer,
    STATE(51), 1,
      sym_coord,
  [381] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [389] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_integer,
    STATE(24), 1,
      sym_coord,
  [399] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_integer,
    STATE(20), 1,
      sym_coord,
  [409] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      sym_identifier,
  [416] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
  [423] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_EQ,
  [430] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_dimensions,
  [437] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      sym_identifier,
  [444] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      sym_integer,
  [451] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_LBRACE,
  [458] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      anon_sym_LBRACE,
  [465] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 1,
      sym_hex_color,
  [472] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_COMMA,
  [479] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      sym_identifier,
  [486] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
  [493] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 1,
      sym_identifier,
  [500] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 1,
      sym_integer,
  [507] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 19,
  [SMALL_STATE(9)] = 38,
  [SMALL_STATE(10)] = 57,
  [SMALL_STATE(11)] = 76,
  [SMALL_STATE(12)] = 95,
  [SMALL_STATE(13)] = 114,
  [SMALL_STATE(14)] = 133,
  [SMALL_STATE(15)] = 152,
  [SMALL_STATE(16)] = 171,
  [SMALL_STATE(17)] = 183,
  [SMALL_STATE(18)] = 197,
  [SMALL_STATE(19)] = 211,
  [SMALL_STATE(20)] = 225,
  [SMALL_STATE(21)] = 237,
  [SMALL_STATE(22)] = 249,
  [SMALL_STATE(23)] = 261,
  [SMALL_STATE(24)] = 271,
  [SMALL_STATE(25)] = 283,
  [SMALL_STATE(26)] = 292,
  [SMALL_STATE(27)] = 301,
  [SMALL_STATE(28)] = 314,
  [SMALL_STATE(29)] = 323,
  [SMALL_STATE(30)] = 332,
  [SMALL_STATE(31)] = 341,
  [SMALL_STATE(32)] = 351,
  [SMALL_STATE(33)] = 361,
  [SMALL_STATE(34)] = 371,
  [SMALL_STATE(35)] = 381,
  [SMALL_STATE(36)] = 389,
  [SMALL_STATE(37)] = 399,
  [SMALL_STATE(38)] = 409,
  [SMALL_STATE(39)] = 416,
  [SMALL_STATE(40)] = 423,
  [SMALL_STATE(41)] = 430,
  [SMALL_STATE(42)] = 437,
  [SMALL_STATE(43)] = 444,
  [SMALL_STATE(44)] = 451,
  [SMALL_STATE(45)] = 458,
  [SMALL_STATE(46)] = 465,
  [SMALL_STATE(47)] = 472,
  [SMALL_STATE(48)] = 479,
  [SMALL_STATE(49)] = 486,
  [SMALL_STATE(50)] = 493,
  [SMALL_STATE(51)] = 500,
  [SMALL_STATE(52)] = 507,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sprite_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sprite_decl_repeat1, 2, 0, 0),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sprite_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sprite_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sprite_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sprite_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sprite_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sprite_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sprite_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sprite_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cell, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cell, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_circle_op, 4, 0, 10),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_circle_op, 4, 0, 10),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fill_op, 2, 0, 5),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fill_op, 2, 0, 5),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pixel_op, 3, 0, 7),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pixel_op, 3, 0, 7),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_flip_op, 2, 0, 6),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_flip_op, 2, 0, 6),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rect_op, 4, 0, 9),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rect_op, 4, 0, 9),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_line_op, 4, 0, 9),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_op, 4, 0, 9),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_palette_decl_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_palette_decl_repeat1, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_coord, 3, 0, 8),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_palette_decl, 5, 0, 1),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sprite_decl, 5, 0, 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sprite_decl, 6, 0, 2),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sprite_decl, 7, 0, 2),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_palette_decl, 4, 0, 1),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_palette_entry, 3, 0, 3),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [149] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_palette_attr, 3, 0, 4),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pixel_dsl(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "pixel_dsl",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
