// Generates a high-res (96x96) kraken sprite as a Pixel-DSL .pix file.
// Tentacles are sampled along Catmull-Rom curves with tapering radius and
// suckers; the mantle/head + face are composed from filled circles.
import { writeFileSync } from "node:fs";

const W = 96;
const H = 96;
const out = [];
const emit = (s) => out.push(s);

const R = (n) => Math.round(n);
const inB = (x, y) => x >= 0 && x < W && y >= 0 && y < H;

// ---- Catmull-Rom spline sampling ----------------------------------------
function catmull(p0, p1, p2, p3, t) {
	const t2 = t * t;
	const t3 = t2 * t;
	return {
		x:
			0.5 *
			(2 * p1.x +
				(-p0.x + p2.x) * t +
				(2 * p0.x - 5 * p1.x + 4 * p2.x - p3.x) * t2 +
				(-p0.x + 3 * p1.x - 3 * p2.x + p3.x) * t3),
		y:
			0.5 *
			(2 * p1.y +
				(-p0.y + p2.y) * t +
				(2 * p0.y - 5 * p1.y + 4 * p2.y - p3.y) * t2 +
				(-p0.y + 3 * p1.y - 3 * p2.y + p3.y) * t3),
	};
}

function sampleCurve(pts, perSeg = 14) {
	const P = [pts[0], ...pts, pts[pts.length - 1]];
	const res = [];
	for (let i = 1; i < P.length - 2; i++) {
		for (let j = 0; j < perSeg; j++) {
			res.push(catmull(P[i - 1], P[i], P[i + 1], P[i + 2], j / perSeg));
		}
	}
	res.push(pts[pts.length - 1]);
	return res;
}

// ---- A tentacle: outline pass, skin pass, shading + suckers --------------
// dir = +1 suckers face one normal side, -1 the other.
function tentacle(pts, rBase, rTip, dir) {
	const s = sampleCurve(pts);
	const n = s.length;
	const radius = (i) => {
		const f = i / (n - 1);
		// ease so the taper holds thickness then narrows near the tip
		return rTip + (rBase - rTip) * (1 - f) ** 1.25;
	};

	// outline (dark silhouette, radius+1)
	emit(`  // tentacle outline`);
	for (let i = 0; i < n; i++) {
		const r = Math.max(1, R(radius(i)) + 1);
		emit(`  circle ${R(s[i].x)},${R(s[i].y)} ${r} K`);
	}
	// skin fill
	emit(`  // tentacle skin`);
	for (let i = 0; i < n; i++) {
		const r = Math.max(1, R(radius(i)));
		emit(`  circle ${R(s[i].x)},${R(s[i].y)} ${r} s`);
	}
	// top-side highlight ridge
	emit(`  // tentacle highlight`);
	for (let i = 0; i < n; i += 2) {
		const r = radius(i);
		if (r < 2.2) continue;
		// tangent
		const a = s[Math.max(0, i - 1)];
		const b = s[Math.min(n - 1, i + 1)];
		let nx = -(b.y - a.y);
		let ny = b.x - a.x;
		const len = Math.hypot(nx, ny) || 1;
		nx /= len;
		ny /= len;
		const hx = R(s[i].x - nx * (r * 0.45) * dir);
		const hy = R(s[i].y - ny * (r * 0.45) * dir);
		if (inB(hx, hy)) emit(`  pixel ${hx},${hy} h`);
	}
	// suckers along the underside
	emit(`  // suckers`);
	for (let i = 2; i < n; i += 3) {
		const r = radius(i);
		if (r < 1.6) continue;
		const a = s[Math.max(0, i - 1)];
		const b = s[Math.min(n - 1, i + 1)];
		let nx = -(b.y - a.y);
		let ny = b.x - a.x;
		const len = Math.hypot(nx, ny) || 1;
		nx /= len;
		ny /= len;
		const off = Math.max(0, r - 1.3);
		const sx = R(s[i].x + nx * off * dir);
		const sy = R(s[i].y + ny * off * dir);
		if (inB(sx, sy)) {
			emit(`  pixel ${sx},${sy} c`);
			// little shadow under the sucker
			const dx = R(s[i].x + nx * (off + 1) * dir);
			const dy = R(s[i].y + ny * (off + 1) * dir);
			if (inB(dx, dy)) emit(`  pixel ${dx},${dy} p`);
		}
	}
}

// ---- HEADER --------------------------------------------------------------
emit(
	`// Kraken — high-res 96x96 sea monster. Bulbous mantle, two glaring eyes,`,
);
emit(
	`// a parrot-beak, and eight tapering, suckered tentacles over deep water.`,
);
emit(`// Generated by scripts/gen-kraken.mjs (Catmull-Rom tentacle curves).`);
emit(``);
emit(`palette kraken {`);
emit(`  deep   D #06121c`);
emit(`  water  w #103445`);
emit(`  wavehi W #1f5a72`);
emit(`  foam   F #6fb6c9`);
emit(`  ink    K #0a0512`);
emit(`  skndk  d #3a1452`);
emit(`  skin   s #6a2a92`);
emit(`  sknhi  h #a857cf`);
emit(`  sknbr  b #d28ce6`);
emit(`  belly  l #e6a9cf`);
emit(`  suck   c #f3c9e2`);
emit(`  suckdk p #b86a98`);
emit(`  eye    e #ffd23f`);
emit(`  eyedk  o #d98a18`);
emit(`  beak   n #1a0d22`);
emit(`  glint  g #fff8da`);
emit(`}`);
emit(``);
emit(`sprite kraken ${W}x${H} palette=kraken {`);

// ---- WATER BACKGROUND ----------------------------------------------------
emit(`  // ---- ocean ----`);
emit(`  fill w`);
emit(`  rect 0,0 ${W - 1},10 W`); // sunlit surface
emit(`  rect 0,11 ${W - 1},16 w`);
emit(`  rect 0,70 ${W - 1},${H - 1} D`); // dark depths
emit(`  rect 0,62 ${W - 1},69 deep`.replace("deep", "D")); // (kept simple)
// scattered bubbles / light specks
const bubbles = [
	[8, 6],
	[20, 4],
	[33, 8],
	[60, 5],
	[74, 7],
	[88, 4],
	[14, 22],
	[82, 26],
	[5, 40],
	[90, 48],
	[48, 3],
];
for (const [x, y] of bubbles) emit(`  pixel ${x},${y} F`);

// ---- TENTACLES (drawn first so the head overlaps their bases) -----------
// Eight tentacles fanning out from a base around (48,52).
emit(`  // ======== TENTACLES ========`);

// Far-left, hooking upward
tentacle(
	[
		{ x: 40, y: 54 },
		{ x: 26, y: 52 },
		{ x: 15, y: 46 },
		{ x: 10, y: 34 },
		{ x: 14, y: 23 },
		{ x: 24, y: 19 },
		{ x: 31, y: 24 },
	],
	7,
	1,
	-1,
);

// Left, sweeping down-left
tentacle(
	[
		{ x: 42, y: 58 },
		{ x: 30, y: 64 },
		{ x: 20, y: 70 },
		{ x: 13, y: 80 },
		{ x: 9, y: 92 },
	],
	7,
	1,
	1,
);

// Left-center, curling down
tentacle(
	[
		{ x: 46, y: 62 },
		{ x: 40, y: 72 },
		{ x: 37, y: 82 },
		{ x: 39, y: 92 },
	],
	7,
	1,
	1,
);

// Center-left short, tucked forward
tentacle(
	[
		{ x: 48, y: 64 },
		{ x: 50, y: 76 },
		{ x: 47, y: 88 },
	],
	6,
	1,
	-1,
);

// Center-right short, tucked forward
tentacle(
	[
		{ x: 50, y: 64 },
		{ x: 56, y: 75 },
		{ x: 58, y: 88 },
	],
	6,
	1,
	1,
);

// Right-center, curling down (mirror of left-center)
tentacle(
	[
		{ x: 52, y: 62 },
		{ x: 60, y: 72 },
		{ x: 64, y: 83 },
		{ x: 62, y: 92 },
	],
	7,
	1,
	-1,
);

// Right, sweeping down-right
tentacle(
	[
		{ x: 56, y: 58 },
		{ x: 70, y: 64 },
		{ x: 80, y: 72 },
		{ x: 86, y: 82 },
		{ x: 90, y: 92 },
	],
	7,
	1,
	-1,
);

// Far-right, hooking upward (mirror of far-left)
tentacle(
	[
		{ x: 58, y: 54 },
		{ x: 72, y: 52 },
		{ x: 83, y: 46 },
		{ x: 88, y: 34 },
		{ x: 84, y: 23 },
		{ x: 74, y: 19 },
		{ x: 67, y: 24 },
	],
	7,
	1,
	1,
);

// ---- HEAD / MANTLE -------------------------------------------------------
emit(`  // ======== MANTLE / HEAD ========`);
// silhouette
emit(`  circle 49,40 25 K`); // big rounded dome (outline)
emit(`  circle 49,40 24 s`); // skin
// lower jaw / face mass blending into tentacle crown
emit(`  circle 49,58 19 K`);
emit(`  circle 49,58 18 s`);

// shading: darker underside, lighter crown
emit(`  // mantle shading`);
emit(`  circle 49,52 21 d`); // shadow lower half
emit(`  circle 44,28 12 h`); // upper-left highlight
emit(`  circle 41,22 7 b`); // bright crown spot
emit(`  pixel 38,20 g`);
emit(`  circle 60,30 6 h`); // secondary highlight right
// belly/forehead sheen line
emit(`  circle 49,40 24 .`.replace(".", "s")); // (no-op keep skin)
// re-light the face center so eyes sit on lit skin
emit(`  circle 49,42 16 s`);
emit(`  circle 49,40 13 h`);

// bumps / warts on the mantle
const warts = [
	[34, 33],
	[63, 36],
	[40, 50],
	[57, 50],
	[49, 30],
	[30, 45],
	[68, 45],
];
for (const [x, y] of warts) {
	emit(`  circle ${x},${y} 2 d`);
	emit(`  pixel ${x - 1},${y - 1} b`);
}

// ---- FACE ----------------------------------------------------------------
emit(`  // ======== FACE ========`);
// angry brow ridges
emit(`  line 33,38 46,44 d`);
emit(`  line 65,38 52,44 d`);
emit(`  line 33,37 46,43 K`);
emit(`  line 65,37 52,43 K`);

// eyes (left, right)
for (const [ex, ey, dir] of [
	[40, 49, -1],
	[58, 49, 1],
]) {
	emit(`  circle ${ex},${ey} 7 K`); // socket
	emit(`  circle ${ex},${ey} 6 e`); // iris
	emit(`  circle ${ex},${ey} 4 o`); // iris depth
	emit(`  circle ${ex + dir},${ey + 1} 3 K`); // pupil (slit-ish, offset)
	emit(`  circle ${ex + dir},${ey + 1} 1 n`);
	emit(`  pixel ${ex - 2},${ey - 2} g`); // glint
	emit(`  pixel ${ex - 3},${ey - 1} g`);
}

// beak / mouth (parrot-like) between & below the eyes
emit(`  // beak`);
emit(`  circle 49,62 6 K`);
emit(`  circle 49,61 5 d`);
emit(`  line 49,57 49,66 n`); // central seam
emit(`  line 45,60 49,66 n`); // left mandible edge
emit(`  line 53,60 49,66 n`); // right mandible edge
emit(`  pixel 49,58 b`);
emit(`  pixel 46,62 l`);
emit(`  pixel 52,62 l`);

// brow horns / frills atop the mantle
emit(`  // crown frills`);
emit(`  line 36,20 32,12 K`);
emit(`  line 36,20 33,13 s`);
emit(`  line 62,20 66,12 K`);
emit(`  line 62,20 65,13 s`);
emit(`  line 49,16 49,8 K`);
emit(`  line 49,16 49,9 s`);
emit(`  pixel 49,8 b`);
emit(`  pixel 32,12 b`);
emit(`  pixel 66,12 b`);

emit(`}`);

writeFileSync(
	new URL("../examples/kraken.pix", import.meta.url),
	out.join("\n"),
);
console.log(`wrote examples/kraken.pix (${out.length} lines)`);
